=head0 Aspectos esenciales de Perl

=head1 Introducción

Perl tiene unos 23 años hasta ahora. El lenguaje ha evolucionado desde una
herramienta simple para la administración de sistemas tomando cosas de shell 
scripting y C (Perl 1) hasta convertirse en un poderoso lenguaje de propósito 
general (Perl 5), consistente, coherente, cambiando el paradigma de programación 
en general con la intensión de mantenerse por otros 25 años. (Perl 6) 

Aun así, la mayoría de los programas en el mundo, escritos en Perl 5, aprovechan
muy poco las características del lenguaje. Usted C<puede> escribir programas en Perl 5 como si estuviera en Perl 4 (o Perl 3 o 2 o 1), pero los programas que 
aprovechan todo el increíble poder del mundo de Perl 5 que la comunidad ha 
inventado, y mejorado, son mas cortos, rápidos, mas poderosos, y fáciles de 
mantener que sus alternativas en anteriores versiones. 

=head1 Instalando Perl

=begin sidebar

Normalmente los sistemas operativos tipo Unix, se distribuyen con una versión de Perl. Si usted desea tener una versión en específico de Perl, entonces le sugerimos el uso de PerlBrew.

Acontinuación, se indica como instalar Perl en una máquina con Debian Lenny. 

=begin programlisting

    aptitude install perl

=end programlisting


=head1 Detalles de la instalación de Perl.

Z<Detalles de la instalación de Perl.>
X<instalación>

=head1 Escribiendo Código: Creando archivos de código. 
Z<Escribiendo Código: Creando archivos de código>

=head1 Escribiendo Código: Declaraciones.
Z<Escribiendo Código: Declaraciones>

=head1 Escribiendo Código: Encontrando el interprete de Perl. 
Z<Escribiendo Código: Encontrando el interprete de Perl>

=head1 Escribiendo Código: Encontrando los módulos de Perl. 
Z<Escribiendo Código: Encontrando los módulos de Perl>

=head1 Ejecutando Código: Usando los switches de la linea de comandos. 
Z<Ejecutando Código: Usando los switches de la linea de comandos>

=head1 Ejecutando Código: Usando el switch -w para las alertas. 
Z<Ejecutando Código: Usando el switch -w para las alertas>

=head1 Ejecutando Código: Usando el switch -e para ejecutar código desde la linea de comandos. 
Z<Ejecutando Código: Usando el switch -e para ejecutar código desde la linea de comandos>

=head1 Ejecutando Código: Usando el switch -c para chequear la sintaxis. 
Z<Ejecutando Código: Usando el switch -c para chequear la sintaxis>

=head1 Ejecutando Código: Ejecución Interactiva. 
Z<Ejecutando Código: Ejecución Interactiva>

=head1 Habilidades Básicas: Entrada y Salida de Texto. 
Z<Habilidades Básicas: Entrada y Salida de Texto>

=head1 Habilidades Básicas: Usando la función Print.   
Z<Habilidades Básicas: Usando la función Print>

=head1 Habilidades Básicas: Formateando el Texto.  
Z<Habilidades Básicas: Formateando el Texto>

=head1 Habilidades Básicas: Comentando tu código.  
Z<Habilidades Básicas: Comentando tu código>

=head1 Habilidades Básicas: Lectura de datos de la entrada estándar.
Z<Habilidades Básicas: Lectura de datos de la entrada estándar>
  
=head1 Habilidades Básicas: Uso de la variable por defecto $_. 
Z<Habilidades Básicas: Uso de la variable por defecto $_>

=head1 Habilidades Básicas: Limpieza los datos leídos de la entrada estándar. 
Z<Habilidades Básicas: Limpieza los datos leídos de la entrada estándar>

=head1 Habilidades Básicas: Fundamentos básicos del diseño de programas en Perl. 
Z<Habilidades Básicas: Fundamentos básicos del diseño de programas en Perl>
