=head1 Ejercicios    

Z<ejercicios06> 

=over 

=item 1. Escriba un programa que imprima cada linea de la entrada que mencione
la palabra C<fred>. Haga un archivo de texto que contenga la palabra fred en
cadenas y nombres que incluyan fred y utilice este archivo como entrada del
programa.  

=item 2. Modifique el programa anterior, para que también haga match con
C<Fred>.

=item 3. Escriba un programa que imprima cada linea de su entrada que contenga
el punto (.), ignore las otras lineas. 

=item 4. Escriba un programa que imprima cada linea que tenga la palabras con
la primera letra en mayúscula, pero no mayúscula sostenida.  

=item 5. Escriba un programa que imprima cada linea que tenga dos caracteres
iguales juntos el uno al otro y que no sea dos espacios en blanco. Debe hacer
match de lineas que contengan cosas como C<Mississippi>, C<Bamm-Bamm>,  o
C<llama>. 

=item 6. Escriba un programa que imprima cualquier linea de la entrada que
contenga los siguientes dos cadenas en la misma linea: C<willma> y C<fred>.



=back
