=head1 Ejercicios

Z<ejercicios_03> 

=over

=item 1. Escriba una función llamada "total" que retorne el total de una lista de números. (Nota: la función no debe realizar algún tipo de I/O, esta debe simplemente procesar sus parámetros y retornar un valor). Complete el siguiente programa de ejemplo con la función "total", el resultado de la sumatoria debe dar 25 para el primer grupo de números.

=begin programlisting

	my @fred = qw{ 1 3 5 7 9 };
	my $fred_total = total(@fred);
	print "El total de \@fred es $fred_total.\n";
	print "Ingrese algunos números separados por lineas: ";
	my $user_total = total(<STDIN>);
	print "El total para los números ingresados es: $user_total.\n";

=end programlisting

=item 2. Usando la función escrita en el ejercicio anterior, realice un programa que calcule la sumatoria de todos los números del 1 al 1000.

=item 3. Escriba una función llamada &above_average que tome una lista de números y retorne solo aquellos números que estén por encima del promedio (Nota: escriba otra función que calcule el promedio de varios números dividiendo el total de la sumatoria de los números por el numero de items). Use su función para probar el siguiente programa:

=begin programlisting

	my @fred = above_average(1..10);
	print "\@fred es @fred\n";
	print "(Debe ser 6 7 8 9 10)\n";
	my @barney = above_average(100, 1..10);
	print "\@barney es @barney\n";
	print "(Debe ser solo 100)\n";

=end programlisting

=item 4. Escriba una función llamada "saludo", que de la bienvenida a una persona por su nombre y que ademas diga el nombre de la ultima persona saludada, ejemplo:

	saludo("Fred");
	saludo("Barney");

Esto debe escribir lo siguiente:

	Hola Fred! Eres el primero aquí!
	Hola Barney! Fred también esta aquí!

=item 5. Modifique el programa anterior para que imprima los nombres de todas las personas que han sido previamente saludadas.

	saludo("Fred");
	saludo("Barney");
	saludo("Wilma");
	saludo("Betty");

La salida debe ser como lo siguiente:

	Hola Fred! Eres el primero aquí!
	Hola Barney! He visto a: Fred
	Hola Wilma! He visto a: Fred Barney
	Hola Betty! He visto a: Fred Barney Wilma

=back
