=head1 Repuestas a Ejercicios del Capitulo 03

Z<respuestas_03> 

=over

=item 1. Una forma de hacerlo:

=begin programlisting

	sub total {
		my $sum;
		foreach (@_) {
			$sum += $_;
		}
		$sum;
	}

=end programlisting

=item 2. Una forma de hacerlo:

=begin programlisting

	# Recuerde incluir la funcion &total del ejercicio pasado!
	print "La sumatoria de los numeros del 1 al 1000 es ", total(1..1000), ".\n";

=end programlisting

=item 3. Una forma de hacer este ejercicio es:

=begin programlisting

	sub average {
		if (@_ == 0) { return }
		my $count = @_;
		my $sum = total(@_);
		$sum/$count;
	}

	sub above_average {
		my $average = average(@_);
		my @list;
		foreach my $element (@_) {
			if ($element > $average) {
				push @list, $element;
			}
		}
		@list;
	}

=end programlisting

=item 4. Una forma de hacer este ejercicio es:

=begin programlisting

	saludo('Fred');
	saludo('Barney');
	
	sub saludo {
		state $last_person;
		my $name = shift;
		print "Hola $name! ";
		if (defined $last_person) {
			print "$last_person tambien esta aqui!\n";
		} else {
			print "Eres el primero aqui!\n";
		}
		$last_person = $name;
	}

=end programlisting

=item 5. Una forma de hacerlo:

=begin programlisting

	saludo('Fred');
	saludo('Barney');
	saludo('Wilma');
	saludo('Betty');
	
	sub saludo {
		state @names;
		my $name = shift;
		print "Hola $name! ";
		if (@names) {
			print "He visto a: @names\n";
		} else {
			print "Eres el primero aqui!\n";
		}
		push @names, $name;
	}


=end programlisting

=back
